name: build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_call:

jobs:
  check:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  build-docker-images:
    uses: ./.github/workflows/build-docker-image.yml
    secrets:
      PUBLISH_TO_GITHUB_REPO_TOKEN: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
      REGISTRY_PASSWORD_DOCKER: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
    with:
      push-images: false
      snapshot: true
