name: Release

on:
  release:
    types:
      - created

jobs:
  check:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      fetch-depth: "0"

  build:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - run: go tool goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: packages
          path: |
            dist/*.deb
            dist/*.rpm
          if-no-files-found: error
          retention-days: 1

  publish-packages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        config:
          - publish-to-apt-linux.yml
          - publish-to-rpms.yml
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: packages
          path: dist

      - uses: siakhooi/publish-to-repo-action@9be1278553e6c9c0a48a3b5c5da567e30f1bf895 # v1.0.0
        with:
          token: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
          config-file: ${{ matrix.config }}

  build-docker-images:
    needs: build
    uses: ./.github/workflows/build-docker-image.yml
    secrets:
      PUBLISH_TO_GITHUB_REPO_TOKEN: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
      REGISTRY_PASSWORD_DOCKER: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
    with:
      push-images: true
      snapshot: false
